$("#LaDarrius").click(function(){
    $("#text").html("Does sick kick flips")
    $("#doggo").attr('src',"assets/dog1.svg")
    $("#doggo").removeClass("d-none")
    $("#name").html("LaDarrius Johnson")
    $("#link").attr("href", "Profile-LaDarrius/index.html")
    $("#link").removeClass("d-none")
    $("#link-lamp").attr("href","https://lamp.cse.fau.edu/~ladarriusjoh2019/p2/")
    $("#link-lamp").removeClass("d-none")
})
$("#Nicholas").click(function(){
    $("#text").html("Posses heat vision")
    $("#doggo").attr('src',"assets/dog2.svg")
    $("#doggo").removeClass("d-none")
    $("#name").html("Nicholas Le")
    $("#link").attr("href", "profile-Nicholas/index.html")
    $("#link").removeClass("d-none")
    $("#link-lamp").attr("href","https://lamp.cse.fau.edu/~nle2019/p2/index.html")
    $("#link-lamp").removeClass("d-none")
})
$("#James").click(function(){
    $("#text").html("Close-Up Magic Expert")
    $("#doggo").attr('src',"assets/dog3.svg")
    $("#doggo").removeClass("d-none")
    $("#name").html("James Macdonald")
    $("#link").attr("href", "Profile-James/index.html")
    $("#link").removeClass("d-none")
    $("#link-lamp").attr("href","https://lamp.cse.fau.edu/~macdonaldj2016/p2/")
    $("#link-lamp").removeClass("d-none")
})
$("#Michael").click(function(){
    $("#text").html("Three goblins in a large coat")
    $("#doggo").attr('src',"assets/dog4.svg")
    $("#doggo").removeClass("d-none")
    $("#name").html("Michael Romero")
    $("#link").attr("href", "profile-Michael/index.html")
    $("#link").removeClass("d-none")
    $("#link-lamp").attr("href","https://lamp.cse.fau.edu/~michaelromer2020/")
    $("#link-lamp").removeClass("d-none")
})
$("#Dennis").click(function(){
    $("#text").html("Cybermancer with a gun for a left hand")
    $("#doggo").attr('src',"assets/dog5.svg")
    $("#doggo").removeClass("d-none")
    $("#name").html("Dennis Sonjaco")
    $("#link").attr("href", "Profile-Dennis/index.html")
    $("#link").removeClass("d-none")
    $("#link-lamp").attr("href","https://lamp.cse.fau.edu/~dsonjaco2018/p2/")
    $("#link-lamp").removeClass("d-none")
})
$("#Ethan").click(function(){
    $("#text").html("Loose cannon with nothing left to lose")
    $("#doggo").attr('src',"assets/dog6.svg")
    $("#doggo").removeClass("d-none")
    $("#name").html("Ethan Fisher")
    $("#link").attr("href", "Profile-Ethan/index.html")
    $("#link").removeClass("d-none")
    $("#link-lamp").attr("href","https://lamp.cse.fau.edu/~efisher2016/p1/")
    $("#link-lamp").removeClass("d-none")
})